# Generated by Django 5.2.6 on 2025-09-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='AuthUser',
        ),
    ]
